name: SixtysixStreaks
options:
  bundleIdPrefix: com.sixtysixstreaks
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_CFBundleDisplayName: "66-Day Streak"

targets:
  SixtysixStreaks:
    type: application
    platform: iOS
    sources:
      - SixtysixStreaks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sixtysixstreaks.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "66-Day Streak"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: false
        ASSETCATALOG_COMPILER_APPICON_NAME: SixtysixStreaksIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: true
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
